# Generated by Django 6.0.7 on 2026-10-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Prazo (Ex: Relatório de Maio)')),
                ('data_limite', models.DateField(verbose_name='Data Limite')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Aviso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Prazo Ativo?')),
            ],
        ),
    ]
