# Generated by Django 6.0.7 on 2026-10-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregamensal',
            name='arquivo_anexo_iii',
            field=models.FileField(blank=True, help_text='Plano de Trabalho Mensal', null=True, upload_to='anexos_frequencia/anexo_iii/'),
        ),
        migrations.AddField(
            model_name='entregamensal',
            name='arquivo_anexo_iv',
            field=models.FileField(blank=True, help_text='Declaração Mensal', null=True, upload_to='anexos_frequencia/anexo_iv/'),
        ),
        migrations.AddField(
            model_name='entregamensal',
            name='total_alunos_presentes',
            field=models.PositiveIntegerField(default=0, help_text='Total de estudantes frequentes no presente mês'),
        ),
        migrations.AlterField(
            model_name='entregamensal',
            name='arquivo_anexo_ii',
            field=models.FileField(help_text='Registro de Frequência Mensal assinado', upload_to='anexos_frequencia/anexo_ii/'),
        ),
    ]
