# Generated by Django 6.0.7 on 2026-10-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma', '0002_entregamensal_arquivo_anexo_iii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregamensal',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
