# Generated by Django 6.0.7 on 2026-10-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma', '0002_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregamensal',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado pelo Professor'), ('R', 'Recusado (Necessita Ajuste)'), ('F', 'Auditado e Arquivado')], default='P', max_length=1),
        ),
    ]
